<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v = "urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="cache-control" content="private" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta http-equiv="content-script-type" content="text/javascript" />
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-title" content="Prototype1" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="author" content="Justinmind" />
    <meta name="description" content="Generated by Justinmind on Thu Mar 13 23:36:32 ICT 2014" />
    <title>Prototype1</title>
    <link rel="shortcut icon" type="image/x-icon" href="${pageContext.request.contextPath}/resources/_jim/images/common/favicon.ico" sizes="128x128" />

    <link type="text/css" rel="stylesheet" href="${pageContext.request.contextPath}/review/includes/include-1394728592523.css" />
    <!--[if IE]><link type="text/css" rel="stylesheet" href="${pageContext.request.contextPath}/review/includes/include-1394728592523-ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="${pageContext.request.contextPath}/review/includes/include-1394728592523-ie8.css" /><![endif]-->
    <!--[if lt IE 9]>
      <script type="text/javascript" src="${pageContext.request.contextPath}/resources/_jim/javascript/PIE_IE678.js"></script>
    <![endif]-->
    <!--[if IE 9]>
      <script type="text/javascript" src="${pageContext.request.contextPath}/resources/_jim/javascript/PIE_IE9.js"></script>
    <![endif]-->
    <!--<script type="text/javascript" src="${pageContext.request.contextPath}/resources/external_tools.js"></script>-->
  </head>
  <body class="review offline" tabindex="0">
    <div id="sidepanel" class="hidden">
      <div id="logo" class="section"><img src="${pageContext.request.contextPath}/resources/_jim/images/sidepanel/logo.png" alt="logo" /></div>
      <div id="info" class="section">
          <div class="title">
          	<span>Prototype</span>
          	<span>Screen</span>
          </div>
          <div class="line"></div>
          <div class="names">
            <span id="projectname" title="Prototype1">Prototype1</span>
            <span id="canvasname"></span>
          </div>
      </div>
      <div class="highlight section">
        <div id="highlight-button" class="button firer">Highlight interactive areas</div>
        <div class="styled-select">
          <select id="highlight-select" class="highlight-select" onchange="this.blur()">
            <option value=".click, .toggle, .dblclick, .rightclick, .mouseenter, .mouseleave, .mouseover, .drag, .change, .focusin, .focusout, .swipeup, .swipedown, .swipeleft, .swiperight, .swipeleftup, .swipeleftdown, .swiperightup, .swiperightdown, .taphold">All</option> <option value=".click, .toggle">Click/Tap</option> <option value=".dblclick">Double Click</option> <option value=".rightclick">Right Click</option> <option value=".mouseenter, .mouseleave, .mouseover">Mouse Over</option> <option value=".change">Change</option> <option value=".focusin, .focusout">Focus In/Out</option> <option value=".drag">Drag</option> <option value=".taphold">Tap & Hold</option> <option value=".swipeup, .swipedown, .swipeleft, .swiperight, .swipeleftup, .swipeleftdown, .swiperightup, .swiperightdown">Swipe</option> 
          </select>
        </div>
      </div>
      <div class="screens section">
        <div class="screentitle">
          <div class="title">Screens</div>
          <div class="toggle open"></div>
        </div>
        <div id="navigation" class="rounded-border">
          <ul id="navigationtree">
            <li class="leaf" title="Home">
              <ins class="icon">&nbsp;</ins><a href="screens/e144d61f-b155-47cc-bf0b-842a70dae4af" tabindex="-1">Home</a>
            </li>
            <li class="leaf" title="contact">
              <ins class="icon">&nbsp;</ins><a href="screens/9390cc95-7713-47d9-875b-142fb75a7294" tabindex="-1">contact</a>
            </li>
            <li class="leaf" title="admin_ loggedin">
              <ins class="icon">&nbsp;</ins><a href="screens/b4d769f2-c0fa-4d7a-92d4-f6e1f36ca555" tabindex="-1">admin_ loggedin</a>
            </li>
            <li class="leaf" title="employee_loggedin">
              <ins class="icon">&nbsp;</ins><a href="screens/073f4bd0-6dcd-43d3-b38d-f93051bf4c4e" tabindex="-1">employee_loggedin</a>
            </li>
            <li class="leaf" title="Health plans">
              <ins class="icon">&nbsp;</ins><a href="screens/6754f284-5b0c-479f-96c4-e97958f93a7a" tabindex="-1">Health plans</a>
            </li>
            <li class="leaf" title="About us">
              <ins class="icon">&nbsp;</ins><a href="screens/13f89107-5c2f-4515-a766-088944a36cfb" tabindex="-1">About us</a>
            </li>
            <li class="leaf" title="Mission & values">
              <ins class="icon">&nbsp;</ins><a href="screens/620b4236-46e8-44fc-a79c-c6532aca547c" tabindex="-1">Mission &amp; values</a>
            </li>
            <li class="leaf" title="Health plans - choose plan">
              <ins class="icon">&nbsp;</ins><a href="screens/4a62240e-9bcb-465a-afa2-e7cfb50e75e6" tabindex="-1">Health plans - choose plan</a>
            </li>
            <li class="leaf" title="Plan detail">
              <ins class="icon">&nbsp;</ins><a href="screens/69ae3315-bba3-4578-8229-2240341ca672" tabindex="-1">Plan detail</a>
            </li>
            <li class="leaf" title="Health plans - medical history">
              <ins class="icon">&nbsp;</ins><a href="screens/deb9bdf6-f097-42d1-9924-ea3790c7b7f9" tabindex="-1">Health plans - medical history</a>
            </li>
            <li class="leaf" title="Health plans - payment">
              <ins class="icon">&nbsp;</ins><a href="screens/272db33c-1f0b-4641-8582-538d89e9549a" tabindex="-1">Health plans - payment</a>
            </li>
            <li class="leaf" title="Plan detail 2">
              <ins class="icon">&nbsp;</ins><a href="screens/9325ba04-54b5-457a-8082-6c2b74316ff7" tabindex="-1">Plan detail 2</a>
            </li>
            <li class="leaf last" title="Health plans - payment 2">
              <ins class="icon">&nbsp;</ins><a href="screens/2b35da45-5514-4dd6-abc8-8ac5b6a29c5e" tabindex="-1">Health plans - payment 2</a>
            </li>
          </ul>
        </div>
      </div>
      <div id="comments" class="section">
        <div class="commentstitle">
          <div class="title">Comments</div>
          <div class="toggle open"></div>
        </div>
        <div class="comment-all">
          <div id="simulation-btns">
            <div id="navigate-btn" class="button firer selected">Navigate</div>
            <div id="comment-btn" class="button firer">Add comment</div>
            <div class="clear"></div>
          </div>
          <div id="search" class="rounded-border"><span id="search-btn" class="firer"></span><input id="search-field" class="firer" type="text" accesskey="s" value="" placeholder="search comments" name="search" /></div>
          <div id="scope-btns">
            <div id="scope-all-btn" class="tabs firer">All Screens</div>
            <div id="scope-border-left"></div>
            <div id="scope-screen-btn" class="tabs firer selected">Current Screen</div>
            <div id="scope-border-right"></div>
            <div class="clear"></div>
          </div>
          <div id="comment-grid"></div>
        </div>
      </div>
      <div id="toggle-panel-btn" class="firer">&nbsp;</div>
    </div>
    <div id="jim-mainWindow">
        <div id="toppanel" class="hidden" onselectstart="return false;">
          <div id="control-bar">
            <div id="rotateDevice" class="hidden">Rotate device</div>
            <div class="hidden">
              <div class="titlecontrol">Gesture tool:</div>
              <div class="styled-select">
                <select id="gestureTool" onchange="this.blur()">
                  <option value="0" selected="selected">One finger</option>
                  <option value="1">Two fingers (pinch)</option>
                  <option value="2">Two fingers (rotate)</option>
                </select>
              </div>
            </div>
            <div class="hidden">
              <div class="titlecontrol">Zoom:</div>
              <div class="styled-select">
                <select id="zoomValue" onchange="this.blur()">
                  <option value="0">50%</option>
                  <option value="1">75%</option>
                  <option value="2" selected="selected">100%</option>
                  <option value="3">150%</option>
                </select>
              </div>
            </div>
          </div>
        </div>
        <div id="jim-body" class="full web" >
            <div id="simulation" class="firer"></div>

        </div>
    </div>
    <div id="chromeTransfer" class="hidden"></div>
    <div id="blockui" class="hidden">
      <div id="dialog" class="hidden">
        <div id="title">New comment <span id="dialog-close" class="firer" title="close">&nbsp;</span></div>
        <div id="content">
          <textarea class="annotation firer" rows="2" placeholder="Leave a comment..."></textarea>
          <form class="attachment firer" enctype="multipart/form-data" method="post">
            <span class="filename"><a class="action">Attach file (&lt; 1MB)</a></span>
            <input type="hidden" name="code" value="" />
            <input type="file" class="file" name="file" size="5" value="" onchange="annotation.updateAttachmentFile(this);" tabindex="-1" />
          </form>
          <button id="dialog-save" class="button firer selected" tabindex="-1">Save</button>
          <button id="dialog-cancel" class="button firer" tabindex="-1">Cancel</button>
          <div class="clear"></div>
        </div>
      </div>
    </div>
    <!-- START COMMENT TEMPLATES -->
    <script type="text/x-jquery-tmpl" id="root-template">
      <![CDATA[
      <div class="root {{? it.isRead === false}}unread{{?}} closed firer rounded-border">
        <input type="hidden" id="parentCode" value="{{=it.code}}" />
        <input type="hidden" id="canvasID" value="{{=it.canvasID}}" />
        <input type="hidden" id="elementID" value="{{=it.elementID}}" />
        <input type="hidden" id="canvasURL" value="{{=it.canvasURL}}" />
        <div class="icon">&nbsp;</div>
        {{=annotation.render(it, "comment-template")}}
        <div class="replies"></div>
        <div class="replier">
          <div class="author">{{=annotation.getCurrentAuthor()}}</div>
            <textarea class="annotation firer">Leave a comment...</textarea>
            <div class="actions">
              <span class="save firer"><a class="action">Save</a></span>
              <span class="cancel firer"> � <a class="action">Cancel</a> � </span>
              <form class="attachment firer" enctype="multipart/form-data" method="post">
                <span class="filename"><a class="action">Attach file (&lt; 1MB)</a></span>
                <input class="file" type="file" onchange="annotation.updateAttachmentFile(this);" value="" size="1" name="file" tabindex="-1" />
              </form>
            </div>
            <div class="clear"></div>
          </div>
        </div>
      </div>
      ]]>
    </script>
    <script type="text/x-jquery-tmpl" id="comment-template">
      <![CDATA[
      <div class="comment">
        <input type="hidden" id="code" value="{{=it.code}}" />
        <span class="author" title="{{=it.author}}">{{=it.author}}</span>
        {{? it.parentCode === 0}}<span class="total">&nbsp;</span>{{?}}
        <span class="date">{{=it.date}}</span>
        <div class="viewmode">
          <div class="text">{{=annotation.toHTML(it.content)}}</div>
          {{? it.fileName !== "" }}<span class="attachment filename firer" onclick="annotation.getAttachmentFile({{=it.code}}, '{{=it.fileName}}');" title="{{=it.fileName}}">{{=it.fileName}}</span>{{?}}
          <div class="actions">
            <span class="reply firer"><a class="action">Reply</a></span>
            {{? annotation.hasPermission(it.author) }}<span class="edit firer"><a class="action"> � </a><a class="action">Edit</a></span><span class="delete firer"><a class="action"> � </a><a class="action">Delete</a></span>{{?}}
          </div>
          <div class="clear"></div>
        </div>
        <div class="editormode">
          <textarea class="annotation firer">{{=it.content}}</textarea>
          <div class="actions">
            <span class="save firer"><a class="action">Save</a></span>
            <span class="cancel firer"><a class="action"> � </a><a class="action">Cancel</a></span>
            <form class="attachment firer" enctype="multipart/form-data" method="post">
              <span class="filename"><a class="action">Attach file (&lt; 1MB)</a></span>
              <input type="file" class="file" name="file" size="1" value="" onchange="annotation.updateAttachmentFile(this);" tabindex="-1" />
            </form>
          </div>
          <div class="clear"></div>
        </div>
      </div>
      ]]>
    </script>
    <script type="text/x-jquery-tmpl" id="message-template">
      <![CDATA[
      {{? it.type === "error" }}
      <div class="message error">
        <div class="container">
          <div class="notice">{{? it.title }}<strong>{{=it.title}}</strong>{{?}}{{=it.text}}</div>
          <strong class="close">x</strong>
        </div>
      </div>
      {{?? it.type === "feedback"}}
      <div class="message feedback">
        <div class="container">
          <div class="notice">{{=it.text}}</div>
          <button type="button" class="ok firer ui-state-default ui-corner-all" tabindex="-1">Ok</button>
          <button type="button" class="cancel firer ui-state-default ui-corner-all" tabindex="-1">Cancel</button>
          <strong class="close">x</strong>
        </div>
      </div>
      {{?}}
      ]]>
    </script>
    <!-- END COMMENT TEMPLATES -->
    <script type="text/javascript" src="${pageContext.request.contextPath}/review/includes/include-1394728592523.js"></script>
    <script type="text/javascript">(function(){jimMain.init("screens/e144d61f-b155-47cc-bf0b-842a70dae4af");})();</script>
  </body>
</html>